const ADD_TASK = 'ADD_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
const ADD_SUB_TASK = 'ADD_SUB_TASK';
const CHANGE_SUB_TASK = 'CHANGE_SUB_TASK'

export {
    ADD_TASK,
    REMOVE_TASK,
    ADD_SUB_TASK,
    CHANGE_SUB_TASK
}

